/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "3d-book": {
    name: "3d-book",
    description: "An interactive 3D book component with page flip animations.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/3d-book.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/3d-book.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "3d-book"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "animated-collection": {
    name: "animated-collection",
    description: "A collection of items with smooth layout transitions and animations.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/animated-collection.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/animated-collection.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-collection"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bottom-menu": {
    name: "bottom-menu",
    description: "A floating bottom navigation menu with smooth interactions.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/bottom-menu.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/bottom-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "bottom-menu"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "day-picker": {
    name: "day-picker",
    description: "A custom day picker component with smooth animations.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/day-picker.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/day-picker.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "day-picker"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "delete-button": {
    name: "delete-button",
    description: "A confirmation button with smooth icon transitions.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/delete-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/delete-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "delete-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "discover-button": {
    name: "discover-button",
    description: "An interactive button with expanding discovery state.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/discover-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/discover-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "discover-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "discrete-tabs": {
    name: "discrete-tabs",
    description: "A tab component with discrete sliding animations.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/discrete-tabs.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/discrete-tabs-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "discrete-tabs"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dynamic-toolbar": {
    name: "dynamic-toolbar",
    description: "A toolbar that adapts its size and layout based on content.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/dynamic-toolbar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "hooks/use-measure.tsx",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/dynamic-toolbar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "dynamic-toolbar"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "expandable-gallery": {
    name: "expandable-gallery",
    description: "A photo gallery with smooth item expansion.",
    type: "registry:component",
    registryDependencies: ["button"],
    files: [{
      path: "registry/default/example/expandable-gallery.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "hooks/use-outside-click.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/expandable-gallery-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "expandable-gallery"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "feature-carousel": {
    name: "feature-carousel",
    description: "A smooth carousel for showcasing product features.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/feature-carousel.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/feature-carousel-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "feature-carousel"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "folder-interaction": {
    name: "folder-interaction",
    description: "A folder management system with drag-and-drop-like feel.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/folder-interaction.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/folder-interaction.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "folder-interaction"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "inline-edit": {
    name: "inline-edit",
    description: "An input that switches between read and edit modes.",
    type: "registry:component",
    registryDependencies: ["input"],
    files: [{
      path: "registry/default/example/inline-edit.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/inline-edit.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "inline-edit"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "list-item": {
    name: "list-item",
    description: "Interactive list items with hover and focus effects.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/list-item.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/list-item.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "list-item"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "morphing-input": {
    name: "morphing-input",
    description: "An input field that morphs between different states.",
    type: "registry:component",
    registryDependencies: ["input"],
    files: [{
      path: "registry/default/example/morphing-input.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/morphing-input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "morphing-input"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "multi-step-form": {
    name: "multi-step-form",
    description: "A dynamic, animated multi-step form with validation.",
    type: "registry:component",
    registryDependencies: ["card","button","input","textarea","select","badge","calendar","popover"],
    files: [{
      path: "registry/default/example/multi-step-form.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/multi-step-form.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "multi-step-form"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pricing-card": {
    name: "pricing-card",
    description: "A focused pricing card layout with clear hierarchy.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/pricing-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/pricing-card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "pricing-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shake-testimonial-card": {
    name: "shake-testimonial-card",
    description: "An eye-catching testimonial card with playful animations.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/shake-testimonial-card.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/shake-testimonial-card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "shake-testimonial-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "smooth-dropdown": {
    name: "smooth-dropdown",
    description: "A dropdown menu with premium layout transitions.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/smooth-dropdown.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/smooth-dropdown.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "smooth-dropdown"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "status-button": {
    name: "status-button",
    description: "A button with animated states for idle, loading, and success.",
    type: "registry:component",
    registryDependencies: ["button"],
    files: [{
      path: "registry/default/example/status-button.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/status-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "status-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "vertical-tabs": {
    name: "vertical-tabs",
    description: "A vertical tab interaction with smooth content switching.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/vertical-tabs.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/demo/vertical-tabs-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "vertical-tabs"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stacked-list": {
    name: "stacked-list",
    description: "An expandable list widget with a stacked layout and smooth morphing transitions.",
    type: "registry:component",
    registryDependencies: ["input","button"],
    files: [{
      path: "registry/default/example/stacked-list.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/stacked-list.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "stacked-list"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "fluid-expanding-grid": {
    name: "fluid-expanding-grid",
    description: "A responsive gallery grid that fluidly shifts and expands items using motion layout.",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/fluid-expanding-grid.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/fluid-expanding-grid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "fluid-expanding-grid"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }