import { spawn } from "child_process";
import { promises as fs } from "fs";
import path from "path";

const registry = JSON.parse(
  await fs.readFile(path.join(process.cwd(), "registry.json"), "utf8"),
);

async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`;
  for (const item of registry.items) {
    const resolveFiles = item.files?.map((file: any) => `${file.path}`);
    if (!resolveFiles) {
      continue;
    }

    const demoPath = `registry/default/demo/${item.name}-demo.tsx`;
    let componentPath = item.files?.[0]?.path ? `@/${item.files[0].path}` : "";

    try {
      await fs.access(path.join(process.cwd(), demoPath));
      componentPath = `@/${demoPath}`;
    } catch (e) {
      // Demo not found, use the first file from registry
    }

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files?.map((file: any) => {
      const filePath = typeof file === "string" ? file : file.path;
      const resolvedFilePath = path.resolve(filePath);
      return typeof file === "string"
        ? `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`;
    })}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "${item.name}"
      return { default: mod.default || mod[exportName] }
    })`
        : "null"
    },
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
  }`;

  console.log(`#️⃣  ${Object.keys(registry.items).length} items found`);

  // Write style index.
  // rimraf.sync(path.join(process.cwd(), "registry/__index__.tsx"))
  await fs.writeFile(path.join(process.cwd(), "registry/__index__.tsx"), index);
}

// async function buildRegistryJsonFile() {
//   // 1. Use the registry as-is since paths are already correct
//   const fixedRegistry = registry

//   // 2. Write the content of the registry to `registry.json`
//   rimraf.sync(path.join(process.cwd(), `registry.json`))
//   await fs.writeFile(
//     path.join(process.cwd(), `registry.json`),
//     JSON.stringify(fixedRegistry, null, 2)
//   )

//   // 3. Copy the registry.json to the www/public/r/styles/default directory.
//   await fs.cp(
//     path.join(process.cwd(), "registry.json"),
//     path.join(
//       process.cwd(),
//       "../www/public/r/styles/default/registry.json"
//     ),
//     { recursive: true }
//   )
// }

function shadcnBin() {
  const ext = process.platform === "win32" ? ".cmd" : "";
  return path.join(process.cwd(), "node_modules", ".bin", `shadcn${ext}`);
}

async function buildRegistry() {
  return new Promise((resolve, reject) => {
    const child = spawn(
      shadcnBin(),
      ["build", "registry.json", "--output", "public/r"],
      {
        cwd: process.cwd(),
        stdio: "inherit",
        shell: process.platform === "win32",
      },
    );

    child.on("error", (error) => {
      reject(
        new Error(
          `Failed to start shadcn (${shadcnBin()}). Run npm install first. ${error.message}`,
        ),
      );
    });

    child.on("exit", (code) => {
      if (code === 0) {
        resolve(undefined);
      } else {
        reject(new Error(`shadcn build exited with code ${code}`));
      }
    });
  });
}

try {
  console.log("🗂️ Building registry/__index__.tsx...");
  await buildRegistryIndex();

  console.log("🏗️ Building registry...");
  await buildRegistry();
} catch (error) {
  console.error(error);
  process.exit(1);
}
